# MACHINE LEARNING LAB ASSIGNMENT


# Convolutional Neural Network Assignment


### NAME     : **MOHIT TALREJA**

### ROLL NO. : **177237**

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import json
from keras.utils.np_utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils


### Loading the MNIST Dataset

In [2]:
features, labels = fetch_openml('mnist_784', version=1, return_X_y=True)

## Preprocessing

Normalizing the feature set:

Each entry is a value between 0 and 255. It is brought to a value between 0 and 1 so as to avoid issues with activation function calculations. (Overflowing when taken directly as it is)

In [3]:
features = (features/255).astype('float32')

Reshaping the 784 pixels into 28 x 28 x 1

In [4]:
features = features.reshape(features.shape[0],28,28,1).astype('float32')

Converting the labels to 1-hot encoded format so as to allow for simple subtraction in delta calculation step at the outputs of the network.

In [5]:
labels = to_categorical(labels)

Splitting into training and testing parts

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.15, random_state=37)

### Convolutional Neural Network Model

**The Kernel**

**Size of Input Layer** = 28 x 28

**Activation Function at Output layer**:
The softmax activation function computes the following - 

$softmax(z) = \frac{exp(z)}{\sum_{j}^{ }exp(z_j)}$

This softmax gives us the probability of each prediction label.







In [7]:
def defineModel(numClasses):
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(28, 28, 1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(numClasses, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

Splitting the test dataset into validation and test parts

In [8]:
X_test, X_val, Y_test, Y_val = train_test_split(X_test, Y_test, test_size=0.1)

Fitting the model

In [9]:
model = defineModel(Y_test.shape[1])
history = model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=10, batch_size=200, verbose=2)

Epoch 1/10
298/298 - 26s - loss: 0.2465 - accuracy: 0.9301 - val_loss: 0.0950 - val_accuracy: 0.9733
Epoch 2/10
298/298 - 26s - loss: 0.0741 - accuracy: 0.9774 - val_loss: 0.0664 - val_accuracy: 0.9790
Epoch 3/10
298/298 - 26s - loss: 0.0521 - accuracy: 0.9841 - val_loss: 0.0571 - val_accuracy: 0.9819
Epoch 4/10
298/298 - 26s - loss: 0.0414 - accuracy: 0.9867 - val_loss: 0.0556 - val_accuracy: 0.9848
Epoch 5/10
298/298 - 26s - loss: 0.0330 - accuracy: 0.9895 - val_loss: 0.0628 - val_accuracy: 0.9800
Epoch 6/10
298/298 - 26s - loss: 0.0282 - accuracy: 0.9908 - val_loss: 0.0600 - val_accuracy: 0.9810
Epoch 7/10
298/298 - 26s - loss: 0.0226 - accuracy: 0.9925 - val_loss: 0.0448 - val_accuracy: 0.9838
Epoch 8/10
298/298 - 26s - loss: 0.0195 - accuracy: 0.9934 - val_loss: 0.0569 - val_accuracy: 0.9838
Epoch 9/10
298/298 - 26s - loss: 0.0159 - accuracy: 0.9947 - val_loss: 0.0421 - val_accuracy: 0.9886
Epoch 10/10
298/298 - 26s - loss: 0.0136 - accuracy: 0.9956 - val_loss: 0.0463 - val_accura

In [10]:
print("Model performance on test data")
results = model.evaluate(X_test, Y_test, batch_size=200)
print("Test loss, Test Accuracy : ", results)

Model performance on test data
48/48 [==============================] - 1s 26ms/step - loss: 0.0359 - accuracy: 0.9906
Test loss, Test Accuracy :  [0.03591638803482056, 0.9905819892883301]


Layer dimensions and weights

In [11]:
for layer in model.layers:
  print("Input shape: ",layer.input_shape)
  print("Output shape: ",layer.output_shape)
  print("Weights: ",layer.weights)

Input shape:  (None, 28, 28, 1)
Output shape:  (None, 24, 24, 32)
Weights:  [<tf.Variable 'conv2d/kernel:0' shape=(5, 5, 1, 32) dtype=float32, numpy=
array([[[[ 1.60868559e-02, -1.91761941e-01, -1.15305856e-02,
           3.96622457e-02,  8.54115654e-03,  9.94615704e-02,
           6.42804354e-02,  2.24053897e-02,  6.37954399e-02,
           1.20875366e-01, -1.26017869e-01,  7.19925687e-02,
           6.15487667e-03,  1.76149458e-02,  2.44997382e-01,
           5.76317497e-03,  1.11861810e-01,  8.98365602e-02,
           2.44264081e-02,  3.30590010e-02,  2.91543137e-02,
           6.17322372e-03,  8.13193023e-02, -2.03940598e-03,
           3.94924991e-02,  1.51276365e-01, -4.39747907e-02,
          -4.27901670e-02, -1.23143233e-01, -2.09812671e-02,
          -2.16406956e-01, -2.08713725e-01]],

        [[ 4.71170470e-02, -1.52854115e-01,  3.51915509e-02,
           3.95208113e-02, -3.03341120e-01,  8.93023796e-03,
          -4.33241017e-02,  5.36723761e-03, -2.85635054e-01,
          

### Loading Handwritten Character Dataset

In [12]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [13]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = "/content/gdrive/My Drive/Kaggle"

In [14]:
#changing the working directory
%cd /content/gdrive/My Drive/Kaggle

/content/gdrive/My Drive/Kaggle


In [15]:
!kaggle datasets download -d sachinpatel21/az-handwritten-alphabets-in-csv-format

 97% 179M/185M [00:04<00:00, 42.0MB/s]
100% 185M/185M [00:04<00:00, 41.4MB/s]


In [16]:
!ls

 az-handwritten-alphabets-in-csv-format.zip  'A_Z Handwritten Data.csv'
'A_Z Handwritten Data'			      kaggle.json


In [17]:
#unzipping the zip files and deleting the zip files
!unzip \*.zip  && rm *.zip

Archive:  az-handwritten-alphabets-in-csv-format.zip
replace A_Z Handwritten Data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: A_Z Handwritten Data.csv  
replace A_Z Handwritten Data/A_Z Handwritten Data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: A_Z Handwritten Data/A_Z Handwritten Data.csv  


In [18]:
!ls

'A_Z Handwritten Data'	'A_Z Handwritten Data.csv'   kaggle.json


In [19]:
df = pd.read_csv('A_Z Handwritten Data.csv')
print(df.shape)

(372450, 785)


Taking subset of the dataset (first 60000 rows)

In [20]:
df = np.array(df)
X = df[:60000,1:785]
Y = df[:60000,0:1]

In [21]:
print(X.shape)
print(Y.shape)
print(np.unique(Y))

(60000, 784)
(60000, 1)
[0 1 2 3 4]


Normalizing feature set entries and converting labels to 1-hot encoded form (same as above done for MNIST dataset)

In [22]:
X = (X/255).astype('float32')
Y = to_categorical(Y)

In [23]:
X = X.reshape(X.shape[0],28,28,1).astype('float32')

In [24]:
CX_train, CX_test, CY_train, CY_test = train_test_split(X, Y, test_size=0.15, random_state=37)

In [25]:
CX_test, CX_val, CY_test, CY_val = train_test_split(CX_test, CY_test, test_size=0.1)

Fitting the model

In [26]:
model = defineModel(CY_test.shape[1])
history = model.fit(CX_train, CY_train, validation_data=(CX_val, CY_val), epochs=10, batch_size=200, verbose=2)

Epoch 1/10
255/255 - 25s - loss: 0.1425 - accuracy: 0.9548 - val_loss: 0.0308 - val_accuracy: 0.9889
Epoch 2/10
255/255 - 25s - loss: 0.0344 - accuracy: 0.9899 - val_loss: 0.0113 - val_accuracy: 0.9978
Epoch 3/10
255/255 - 25s - loss: 0.0212 - accuracy: 0.9940 - val_loss: 0.0102 - val_accuracy: 0.9967
Epoch 4/10
255/255 - 24s - loss: 0.0155 - accuracy: 0.9957 - val_loss: 0.0049 - val_accuracy: 1.0000
Epoch 5/10
255/255 - 25s - loss: 0.0135 - accuracy: 0.9960 - val_loss: 0.0096 - val_accuracy: 0.9967
Epoch 6/10
255/255 - 28s - loss: 0.0096 - accuracy: 0.9972 - val_loss: 0.0049 - val_accuracy: 0.9967
Epoch 7/10
255/255 - 25s - loss: 0.0069 - accuracy: 0.9979 - val_loss: 0.0014 - val_accuracy: 1.0000
Epoch 8/10
255/255 - 25s - loss: 0.0054 - accuracy: 0.9984 - val_loss: 0.0021 - val_accuracy: 1.0000
Epoch 9/10
255/255 - 24s - loss: 0.0036 - accuracy: 0.9991 - val_loss: 0.0015 - val_accuracy: 1.0000
Epoch 10/10
255/255 - 24s - loss: 0.0047 - accuracy: 0.9984 - val_loss: 0.0059 - val_accura

In [27]:
print("Model performance on test data")
results = model.evaluate(CX_test, CY_test, batch_size=200)
print("Test loss, Test Accuracy : ", results)

Model performance on test data
41/41 [==============================] - 1s 26ms/step - loss: 0.0096 - accuracy: 0.9972
Test loss, Test Accuracy :  [0.009607982821762562, 0.9971604943275452]


In [28]:
for layer in model.layers:
  print("Input shape: ",layer.input_shape)
  print("Output shape: ",layer.output_shape)
  print("Weights: ",layer.weights)

Input shape:  (None, 28, 28, 1)
Output shape:  (None, 24, 24, 32)
Weights:  [<tf.Variable 'conv2d_1/kernel:0' shape=(5, 5, 1, 32) dtype=float32, numpy=
array([[[[ 1.20432548e-01, -2.01718900e-02, -6.49384335e-02,
           8.16657320e-02, -7.06758872e-02, -4.33008298e-02,
           3.27401198e-02, -6.49140775e-02, -9.58542153e-02,
           1.59259252e-02, -9.63009596e-02,  7.62658790e-02,
           4.12351862e-02, -1.05420738e-01, -4.73124422e-02,
           9.91806164e-02,  1.82626955e-02,  2.75331829e-02,
           4.88553569e-02, -6.21182732e-02, -8.81635547e-02,
           4.85143717e-03, -3.58585566e-02, -9.09629464e-02,
           2.89934240e-02, -8.92003849e-02,  6.89787371e-03,
          -2.33164713e-01, -6.07458018e-02,  1.10570237e-01,
          -1.09619391e-03, -1.35869160e-03]],

        [[-9.34905931e-02, -2.94045871e-03, -1.66398689e-01,
           1.08318031e-01, -2.27286816e-02, -5.79381809e-02,
          -1.47790592e-02,  1.32697031e-01,  9.26640108e-02,
        